apiVersion: apps/v1
kind: Deployment
metadata:
  name: segwarides
  labels:
    app: segwarides
spec:
  replicas: 1
  selector:
    matchLabels:
      name: segwarides
  template:
    metadata:
      labels:
        name: segwarides
    spec:
      containers:
        - name: app
          imagePullPolicy: "Always"
          # Use images field in a Kustomization to regularly set/update image tag
          image: "lsstsqre/segwarides"
          ports:
            - containerPort: 8080
              name: app
          envFrom:
            - configMapRef:
                name: segwarides
